### ISSUE TITLE
Unclarity in final exam requirements

### ISSUE THREAD

**Issue by davidjaggi** [ipozdeev/digital-tools-for-finance#3]
**Problem:**
There is a mismatch between the exercises and the assignment requirement in the README.

**Example:**
The README mentions *featuring a paper (does not have to be of meaningful content) written in LaTeX, with sections, a table of contents, tables and figures;*

But the LaTex exercises in [Writing in LaText](https://github.com/ipozdeev/digital-tools-for-finance/blob/master/writing-with-latex.md) does not mention a table of content.

**Solution:**
Change either of the requirements or clarify what is expected.

**Comment by ipozdeev** [comment]
good fun! help yourself to extra points =)
exercises are not part of the exam, so please include a ToC in the paper in your final submission

**Comment by davidjaggi** [comment]
Sorry, my bad. I thought that the final exam is just the previous exercises combined.
